/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ModulusCalculation */

#ifndef _Included_ModulusCalculation
#define _Included_ModulusCalculation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ModulusCalculation
 * Method:    calculateModulus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ModulusCalculation_calculateModulus
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
