package com.twist.interfaces.HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, July 10, 2020 7:39:09 PM EAT
*/

public interface HelloOperations 
{
  String sayHello ();
  void shuttdown ();
} // interface HelloOperations
